# Generated by Django 3.2.3 on 2021-06-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_departments_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='sl',
        ),
    ]
