# Generated by Django 3.2.3 on 2021-06-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_departments_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dept_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
