# Generated by Django 3.2.3 on 2021-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_departments_dept_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemtitle', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=200)),
                ('msg', models.TextField()),
                ('website', models.TextField()),
                ('products', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('Idnum', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=300)),
            ],
        ),
    ]
