# Generated by Django 3.2.3 on 2021-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='reply',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
