# Generated by Django 3.2.3 on 2021-06-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tickets_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=100)),
                ('placeholder', models.CharField(max_length=200)),
                ('field_length', models.IntegerField()),
                ('field_required', models.BooleanField(default=False)),
                ('field_status', models.BooleanField(default=False)),
            ],
        ),
    ]
