# Generated by Django 3.2.3 on 2021-06-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_fields_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='knowledgebases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=300)),
            ],
        ),
    ]
