# Generated by Django 3.2.3 on 2021-06-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roles',
            new_name='roless',
        ),
    ]
