# Generated by Django 3.2.3 on 2021-06-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_nusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nusers',
            new_name='nuserss',
        ),
    ]
