# Generated by Django 3.2.3 on 2021-06-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_nusers_nuserss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuserss',
            old_name='password',
            new_name='password1',
        ),
    ]
