from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('dashboard',views.dashboard,name='dashboard'),    
    path('AllTickets',views.AllTickets,name='AllTickets'),
    path('open1',views.open1,name='open1'),
    path('close',views.close,name='close'),
    path('addtickets',views.addtickets,name='addtickets'),
    path('department',views.department,name='department'),
    path('add',views.add,name='add'),
    path('customfield',views.customfield,name='customfield'),
    path('knowledgebase',views.knowledgebase , name='knowledgebase'),
    path('staffs',views.staffs , name='staffs'),
    path('users',views.users,name='users'),
    path('roles',views.roles,name='roles'),
    path('nknowledgebase',views.nknowledgebase,name='nknowledgebase'),
    path('nstaffs',views.nstaffs,name='nstaffs'),
    path('nusers',views.nusers,name='nusers'),
    path('nroles',views.nroles,name='nroles'),
    path('editdept/<int:id>',views.editdept,name='editdept'),
    path('updatedept/<int:id>',views.updatedept,name='updatedept'),
    path('deletedept/<int:id>',views.deletedept,name='deletedept'),
    path('newticket/<str:username>',views.newticket,name='newticket'),
    path('rticket/<int:id>',views.rticket,name='rticket'),
    path('updatetic/<int:id>',views.updatetic,name='updatetic'),
    path('closeticket/<int:id>',views.closeticket,name='closeticket'),
    path('reopentic/<int:id>',views.reopentic,name='reopentic'),
    path('nfield',views.nfield,name='nfield'),
    path('editfield/<int:id>',views.editfield,name='editfield'),
    path('updatefield/<int:id>',views.updatefield,name='updatefield'),
    path('delfield/<int:id>',views.delfield,name='delfield'),
    path('addknw/<str:username>',views.addknw,name='addknw'),
    path('editknw/<int:id>',views.editknw,name='editknw'),
    path('updateknw/<int:id>/<str:username>',views.updateknw,name='updateknw'),
    path('deleteknw/<int:id>',views.deleteknw,name='deleteknw'),
    path('addrole',views.addrole,name='addrole'),
    path('editrole/<int:id>',views.editrole,name='editrole'),
    path('updaterole/<int:id>',views.updaterole,name='updaterole'),
    path('deleterole/<int:id>',views.deleterole,name='deleterole'),
    path('addstaff',views.addstaff,name='addstaff'),
    path('editstaff/<int:id>',views.editstaff,name='editstaff'),
    path('upddatestaff/<int:id>',views.upddatestaff,name='upddatestaff'),
    path('adduser',views.adduser,name='adduser'),
    path('edituser/<int:id>',views.edituser,name='edituser'),
    path('updateuser/<int:id>',views.updateuser,name='updateuser'),
    path('deletenuser/<int:id>',views.deletenuser,name='deletenuser'),


]
